#if !canImport(ObjectiveC)
import XCTest

extension BookishImporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BookishImporterTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BookishImporterTests.__allTests__BookishImporterTests),
    ]
}
#endif
